// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BookingStatus.
const (
	Booked    BookingStatus = "booked"
	Cancelled BookingStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Booked:
		return true
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for InvoiceStatus.
const (
	Failed  InvoiceStatus = "failed"
	Paid    InvoiceStatus = "paid"
	Pending InvoiceStatus = "pending"
	Void    InvoiceStatus = "void"
)

// Valid indicates whether the value is a known member of the InvoiceStatus enum.
func (e InvoiceStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Paid:
		return true
	case Pending:
		return true
	case Void:
		return true
	default:
		return false
	}
}

// Defines values for MemberStatus.
const (
	MemberStatusActive    MemberStatus = "active"
	MemberStatusSuspended MemberStatus = "suspended"
)

// Valid indicates whether the value is a known member of the MemberStatus enum.
func (e MemberStatus) Valid() bool {
	switch e {
	case MemberStatusActive:
		return true
	case MemberStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for MembershipStatus.
const (
	MembershipStatusActive  MembershipStatus = "active"
	MembershipStatusExpired MembershipStatus = "expired"
	MembershipStatusFrozen  MembershipStatus = "frozen"
)

// Valid indicates whether the value is a known member of the MembershipStatus enum.
func (e MembershipStatus) Valid() bool {
	switch e {
	case MembershipStatusActive:
		return true
	case MembershipStatusExpired:
		return true
	case MembershipStatusFrozen:
		return true
	default:
		return false
	}
}

// Attendance defines model for Attendance.
type Attendance struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId     UUID       `json:"branchId"`
	CheckedInAt  Timestamp  `json:"checkedInAt"`
	CheckedOutAt *Timestamp `json:"checkedOutAt,omitempty"`
	CreatedAt    Timestamp  `json:"createdAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id UUID `json:"id"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId     UUID  `json:"memberId"`
	MembershipId *UUID `json:"membershipId,omitempty"`
}

// AttendanceCheckInRequest defines model for AttendanceCheckInRequest.
type AttendanceCheckInRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId UUID `json:"branchId"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`
}

// Booking defines model for Booking.
type Booking struct {
	BookedAt    Timestamp  `json:"bookedAt"`
	CancelledAt *Timestamp `json:"cancelledAt,omitempty"`

	// ClassId Example: 550e8400-e29b-41d4-a716-446655440000
	ClassId   UUID      `json:"classId"`
	CreatedAt Timestamp `json:"createdAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id UUID `json:"id"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID          `json:"memberId"`
	Status   BookingStatus `json:"status"`
}

// BookingCreateRequest defines model for BookingCreateRequest.
type BookingCreateRequest struct {
	// ClassId Example: 550e8400-e29b-41d4-a716-446655440000
	ClassId UUID `json:"classId"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`
}

// BookingStatus defines model for BookingStatus.
type BookingStatus string

// Branch defines model for Branch.
type Branch struct {
	Address   string    `json:"address"`
	CreatedAt Timestamp `json:"createdAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id        UUID      `json:"id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	Name      string    `json:"name"`
	UpdatedAt Timestamp `json:"updatedAt"`
}

// BranchCreateRequest defines model for BranchCreateRequest.
type BranchCreateRequest struct {
	Address   string  `json:"address"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Name      string  `json:"name"`
}

// BranchPage defines model for BranchPage.
type BranchPage struct {
	Items []Branch `json:"items"`

	// NextCursor Opaque cursor for the next page; omitted when this is the last page
	NextCursor *string `json:"nextCursor,omitempty"`
}

// BranchUpdateRequest defines model for BranchUpdateRequest.
type BranchUpdateRequest struct {
	Address   *string  `json:"address,omitempty"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	Name      *string  `json:"name,omitempty"`
}

// Class defines model for Class.
type Class struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId  UUID      `json:"branchId"`
	Capacity  int       `json:"capacity"`
	CreatedAt Timestamp `json:"createdAt"`
	EndsAt    Timestamp `json:"endsAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id        UUID      `json:"id"`
	Name      string    `json:"name"`
	StartsAt  Timestamp `json:"startsAt"`
	TrainerId *UUID     `json:"trainerId,omitempty"`
	UpdatedAt Timestamp `json:"updatedAt"`
}

// ClassCreateRequest defines model for ClassCreateRequest.
type ClassCreateRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId UUID      `json:"branchId"`
	Capacity int       `json:"capacity"`
	EndsAt   Timestamp `json:"endsAt"`
	Name     string    `json:"name"`
	StartsAt Timestamp `json:"startsAt"`

	// TrainerId Example: 550e8400-e29b-41d4-a716-446655440000
	TrainerId *UUID `json:"trainerId,omitempty"`
}

// ClassUpdateRequest defines model for ClassUpdateRequest.
type ClassUpdateRequest struct {
	Capacity *int       `json:"capacity,omitempty"`
	EndsAt   *Timestamp `json:"endsAt,omitempty"`
	Name     *string    `json:"name,omitempty"`
	StartsAt *Timestamp `json:"startsAt,omitempty"`
}

// Error Example: {"code":"member_not_found","error":"member not found"}
type Error struct {
	// Code Stable machine-readable error code.
	Code *string `json:"code,omitempty"`

	// Error Human-readable error message, safe for clients.
	Error string `json:"error"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	AmountCents int64     `json:"amountCents"`
	CreatedAt   Timestamp `json:"createdAt"`
	Currency    string    `json:"currency"`
	DueAt       Timestamp `json:"dueAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id UUID `json:"id"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`

	// MembershipId Example: 550e8400-e29b-41d4-a716-446655440000
	MembershipId UUID          `json:"membershipId"`
	PaidAt       *Timestamp    `json:"paidAt,omitempty"`
	Status       InvoiceStatus `json:"status"`
	UpdatedAt    Timestamp     `json:"updatedAt"`
}

// InvoiceCreateRequest defines model for InvoiceCreateRequest.
type InvoiceCreateRequest struct {
	AmountCents int64     `json:"amountCents"`
	Currency    string    `json:"currency"`
	DueAt       Timestamp `json:"dueAt"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`

	// MembershipId Example: 550e8400-e29b-41d4-a716-446655440000
	MembershipId UUID `json:"membershipId"`
}

// InvoiceStatus defines model for InvoiceStatus.
type InvoiceStatus string

// InvoiceUpdateRequest defines model for InvoiceUpdateRequest.
type InvoiceUpdateRequest struct {
	DueAt  *Timestamp     `json:"dueAt,omitempty"`
	Status *InvoiceStatus `json:"status,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Short-lived Bearer access token carrying the permission set.
	AccessToken string `json:"accessToken"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Opaque rotating credential; consumed and replaced on each refresh.
	RefreshToken string `json:"refreshToken"`
	TokenType    string `json:"tokenType"`
}

// Member defines model for Member.
type Member struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId  UUID                `json:"branchId"`
	CreatedAt Timestamp           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id        UUID         `json:"id"`
	Name      string       `json:"name"`
	Phone     string       `json:"phone"`
	Status    MemberStatus `json:"status"`
	UpdatedAt Timestamp    `json:"updatedAt"`
}

// MemberCreateRequest defines model for MemberCreateRequest.
type MemberCreateRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId UUID                `json:"branchId"`
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Phone    *string             `json:"phone,omitempty"`
}

// MemberStatus defines model for MemberStatus.
type MemberStatus string

// MemberUpdateRequest defines model for MemberUpdateRequest.
type MemberUpdateRequest struct {
	Email  *openapi_types.Email `json:"email,omitempty"`
	Name   *string              `json:"name,omitempty"`
	Phone  *string              `json:"phone,omitempty"`
	Status *MemberStatus        `json:"status,omitempty"`
}

// Membership defines model for Membership.
type Membership struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId  UUID      `json:"branchId"`
	CreatedAt Timestamp `json:"createdAt"`
	ExpiresAt Timestamp `json:"expiresAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id UUID `json:"id"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`

	// PackageId Example: 550e8400-e29b-41d4-a716-446655440000
	PackageId UUID             `json:"packageId"`
	StartsAt  Timestamp        `json:"startsAt"`
	Status    MembershipStatus `json:"status"`
	UpdatedAt Timestamp        `json:"updatedAt"`
}

// MembershipCreateRequest defines model for MembershipCreateRequest.
type MembershipCreateRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId UUID `json:"branchId"`

	// MemberId Example: 550e8400-e29b-41d4-a716-446655440000
	MemberId UUID `json:"memberId"`

	// PackageId Example: 550e8400-e29b-41d4-a716-446655440000
	PackageId UUID `json:"packageId"`
}

// MembershipStatus defines model for MembershipStatus.
type MembershipStatus string

// MembershipUpdateRequest defines model for MembershipUpdateRequest.
type MembershipUpdateRequest struct {
	ExpiresAt *Timestamp        `json:"expiresAt,omitempty"`
	Status    *MembershipStatus `json:"status,omitempty"`
}

// Package defines model for Package.
type Package struct {
	Active    bool      `json:"active"`
	CreatedAt Timestamp `json:"createdAt"`

	// Currency Example: BHD
	Currency     string `json:"currency"`
	DurationDays int    `json:"durationDays"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id         UUID      `json:"id"`
	Name       string    `json:"name"`
	PriceCents int64     `json:"priceCents"`
	UpdatedAt  Timestamp `json:"updatedAt"`
}

// PackageCreateRequest defines model for PackageCreateRequest.
type PackageCreateRequest struct {
	Currency     string `json:"currency"`
	DurationDays int    `json:"durationDays"`
	Name         string `json:"name"`
	PriceCents   int64  `json:"priceCents"`
}

// PackageUpdateRequest defines model for PackageUpdateRequest.
type PackageUpdateRequest struct {
	Active       *bool   `json:"active,omitempty"`
	Currency     *string `json:"currency,omitempty"`
	DurationDays *int    `json:"durationDays,omitempty"`
	Name         *string `json:"name,omitempty"`
	PriceCents   *int64  `json:"priceCents,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Staff defines model for Staff.
type Staff struct {
	Active bool `json:"active"`

	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId  UUID                `json:"branchId"`
	CreatedAt Timestamp           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id          UUID      `json:"id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	Phone       string    `json:"phone"`
	UpdatedAt   Timestamp `json:"updatedAt"`
}

// StaffCreateRequest defines model for StaffCreateRequest.
type StaffCreateRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId    UUID                `json:"branchId"`
	Email       openapi_types.Email `json:"email"`
	Name        string              `json:"name"`
	Permissions *[]string           `json:"permissions,omitempty"`
	Phone       *string             `json:"phone,omitempty"`
}

// StaffUpdateRequest defines model for StaffUpdateRequest.
type StaffUpdateRequest struct {
	Active      *bool                `json:"active,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Name        *string              `json:"name,omitempty"`
	Permissions *[]string            `json:"permissions,omitempty"`
	Phone       *string              `json:"phone,omitempty"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// Trainer defines model for Trainer.
type Trainer struct {
	Active bool `json:"active"`

	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId  UUID                `json:"branchId"`
	CreatedAt Timestamp           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id        UUID      `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	UpdatedAt Timestamp `json:"updatedAt"`
}

// TrainerCreateRequest defines model for TrainerCreateRequest.
type TrainerCreateRequest struct {
	// BranchId Example: 550e8400-e29b-41d4-a716-446655440000
	BranchId UUID                `json:"branchId"`
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Phone    *string             `json:"phone,omitempty"`
}

// TrainerUpdateRequest defines model for TrainerUpdateRequest.
type TrainerUpdateRequest struct {
	Active *bool                `json:"active,omitempty"`
	Email  *openapi_types.Email `json:"email,omitempty"`
	Name   *string              `json:"name,omitempty"`
	Phone  *string              `json:"phone,omitempty"`
}

// UUID Example: 550e8400-e29b-41d4-a716-446655440000
type UUID = openapi_types.UUID

// AttendanceID Example: 550e8400-e29b-41d4-a716-446655440000
type AttendanceID = UUID

// BookingID Example: 550e8400-e29b-41d4-a716-446655440000
type BookingID = UUID

// BranchCursor defines model for BranchCursor.
type BranchCursor = string

// BranchID Example: 550e8400-e29b-41d4-a716-446655440000
type BranchID = UUID

// BranchIDQuery Example: 550e8400-e29b-41d4-a716-446655440000
type BranchIDQuery = UUID

// BranchLimit defines model for BranchLimit.
type BranchLimit = int

// BranchQuery defines model for BranchQuery.
type BranchQuery = string

// ClassID Example: 550e8400-e29b-41d4-a716-446655440000
type ClassID = UUID

// InvoiceID Example: 550e8400-e29b-41d4-a716-446655440000
type InvoiceID = UUID

// MemberID Example: 550e8400-e29b-41d4-a716-446655440000
type MemberID = UUID

// MembershipID Example: 550e8400-e29b-41d4-a716-446655440000
type MembershipID = UUID

// PackageID Example: 550e8400-e29b-41d4-a716-446655440000
type PackageID = UUID

// StaffID Example: 550e8400-e29b-41d4-a716-446655440000
type StaffID = UUID

// TrainerID Example: 550e8400-e29b-41d4-a716-446655440000
type TrainerID = UUID

// TrainerIDQuery Example: 550e8400-e29b-41d4-a716-446655440000
type TrainerIDQuery = UUID

// BadRequest Example: {"code":"member_not_found","error":"member not found"}
type BadRequest = Error

// Conflict Example: {"code":"member_not_found","error":"member not found"}
type Conflict = Error

// InternalError Example: {"code":"member_not_found","error":"member not found"}
type InternalError = Error

// NotFound Example: {"code":"member_not_found","error":"member not found"}
type NotFound = Error

// Unauthorized Example: {"code":"member_not_found","error":"member not found"}
type Unauthorized = Error

// ValidationError Example: {"code":"member_not_found","error":"member not found"}
type ValidationError = Error

// ListBranchesParams defines parameters for ListBranches.
type ListBranchesParams struct {
	// Q Free-text search matching branch name or address as a case-insensitive substring
	Q *BranchQuery `form:"q,omitempty" json:"q,omitempty"`

	// Limit Maximum number of branches to return (default 20, maximum 100)
	Limit *BranchLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous listBranches response for the next page
	Cursor *BranchCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListClassesParams defines parameters for ListClasses.
type ListClassesParams struct {
	// BranchId Filter by branch
	BranchId *BranchIDQuery `form:"branchId,omitempty" json:"branchId,omitempty"`

	// TrainerId Filter by trainer
	TrainerId *TrainerIDQuery `form:"trainerId,omitempty" json:"trainerId,omitempty"`
}

// CheckInJSONRequestBody defines body for CheckIn for application/json ContentType.
type CheckInJSONRequestBody = AttendanceCheckInRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = BookingCreateRequest

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = BranchCreateRequest

// UpdateBranchJSONRequestBody defines body for UpdateBranch for application/json ContentType.
type UpdateBranchJSONRequestBody = BranchUpdateRequest

// CreateClassJSONRequestBody defines body for CreateClass for application/json ContentType.
type CreateClassJSONRequestBody = ClassCreateRequest

// UpdateClassJSONRequestBody defines body for UpdateClass for application/json ContentType.
type UpdateClassJSONRequestBody = ClassUpdateRequest

// CreateInvoiceJSONRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody = InvoiceCreateRequest

// UpdateInvoiceJSONRequestBody defines body for UpdateInvoice for application/json ContentType.
type UpdateInvoiceJSONRequestBody = InvoiceUpdateRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = MemberCreateRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = MemberUpdateRequest

// CreateMembershipJSONRequestBody defines body for CreateMembership for application/json ContentType.
type CreateMembershipJSONRequestBody = MembershipCreateRequest

// UpdateMembershipJSONRequestBody defines body for UpdateMembership for application/json ContentType.
type UpdateMembershipJSONRequestBody = MembershipUpdateRequest

// CreatePackageJSONRequestBody defines body for CreatePackage for application/json ContentType.
type CreatePackageJSONRequestBody = PackageCreateRequest

// UpdatePackageJSONRequestBody defines body for UpdatePackage for application/json ContentType.
type UpdatePackageJSONRequestBody = PackageUpdateRequest

// CreateStaffJSONRequestBody defines body for CreateStaff for application/json ContentType.
type CreateStaffJSONRequestBody = StaffCreateRequest

// UpdateStaffJSONRequestBody defines body for UpdateStaff for application/json ContentType.
type UpdateStaffJSONRequestBody = StaffUpdateRequest

// CreateTrainerJSONRequestBody defines body for CreateTrainer for application/json ContentType.
type CreateTrainerJSONRequestBody = TrainerCreateRequest

// UpdateTrainerJSONRequestBody defines body for UpdateTrainer for application/json ContentType.
type UpdateTrainerJSONRequestBody = TrainerUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CheckIn Check a member in
	// (POST /attendance/check-in)
	CheckIn(c *gin.Context)
	// CheckOut Check a member out
	// (POST /attendance/check-out)
	CheckOut(c *gin.Context)
	// GetAttendance Get an attendance record by ID
	// (GET /attendance/{attendanceId})
	GetAttendance(c *gin.Context, attendanceId AttendanceID)
	// Login Authenticate a staff member
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Log the current session out
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Refresh Rotate a refresh token
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// CreateBooking Book a seat in a class
	// (POST /bookings)
	CreateBooking(c *gin.Context)
	// GetBooking Get a booking by ID
	// (GET /bookings/{bookingId})
	GetBooking(c *gin.Context, bookingId BookingID)
	// CancelBooking Cancel a booking
	// (POST /bookings/{bookingId}/cancel)
	CancelBooking(c *gin.Context, bookingId BookingID)
	// ListBranches List and search branches
	// (GET /branches)
	ListBranches(c *gin.Context, params ListBranchesParams)
	// CreateBranch Create a branch
	// (POST /branches)
	CreateBranch(c *gin.Context)
	// GetBranch Get a branch by ID
	// (GET /branches/{branchId})
	GetBranch(c *gin.Context, branchId BranchID)
	// UpdateBranch Update a branch
	// (PATCH /branches/{branchId})
	UpdateBranch(c *gin.Context, branchId BranchID)
	// ListBranchStaff List staff at a branch
	// (GET /branches/{branchId}/staff)
	ListBranchStaff(c *gin.Context, branchId BranchID)
	// ListBranchTrainers List trainers at a branch
	// (GET /branches/{branchId}/trainers)
	ListBranchTrainers(c *gin.Context, branchId BranchID)
	// ListClasses List classes
	// (GET /classes)
	ListClasses(c *gin.Context, params ListClassesParams)
	// CreateClass Create a class
	// (POST /classes)
	CreateClass(c *gin.Context)
	// DeleteClass Delete a class
	// (DELETE /classes/{classId})
	DeleteClass(c *gin.Context, classId ClassID)
	// GetClass Get a class by ID
	// (GET /classes/{classId})
	GetClass(c *gin.Context, classId ClassID)
	// UpdateClass Update a class
	// (PATCH /classes/{classId})
	UpdateClass(c *gin.Context, classId ClassID)
	// ListClassBookings List bookings for a class
	// (GET /classes/{classId}/bookings)
	ListClassBookings(c *gin.Context, classId ClassID)
	// CreateInvoice Create an invoice
	// (POST /invoices)
	CreateInvoice(c *gin.Context)
	// GetInvoice Get an invoice by ID
	// (GET /invoices/{invoiceId})
	GetInvoice(c *gin.Context, invoiceId InvoiceID)
	// UpdateInvoice Update an invoice
	// (PATCH /invoices/{invoiceId})
	UpdateInvoice(c *gin.Context, invoiceId InvoiceID)
	// ListMembers List all members
	// (GET /members)
	ListMembers(c *gin.Context)
	// CreateMember Create a member
	// (POST /members)
	CreateMember(c *gin.Context)
	// DeleteMember Delete a member
	// (DELETE /members/{memberId})
	DeleteMember(c *gin.Context, memberId MemberID)
	// GetMember Get a member by ID
	// (GET /members/{memberId})
	GetMember(c *gin.Context, memberId MemberID)
	// UpdateMember Update a member
	// (PATCH /members/{memberId})
	UpdateMember(c *gin.Context, memberId MemberID)
	// ListMemberAttendance List a member's attendance records
	// (GET /members/{memberId}/attendance)
	ListMemberAttendance(c *gin.Context, memberId MemberID)
	// ListMemberInvoices List a member's invoices
	// (GET /members/{memberId}/invoices)
	ListMemberInvoices(c *gin.Context, memberId MemberID)
	// ListMemberMemberships List a member's membership history
	// (GET /members/{memberId}/memberships)
	ListMemberMemberships(c *gin.Context, memberId MemberID)
	// CreateMembership Purchase a membership
	// (POST /memberships)
	CreateMembership(c *gin.Context)
	// GetMembership Get a membership by ID
	// (GET /memberships/{membershipId})
	GetMembership(c *gin.Context, membershipId MembershipID)
	// UpdateMembership Update a membership
	// (PATCH /memberships/{membershipId})
	UpdateMembership(c *gin.Context, membershipId MembershipID)
	// ListPackages List membership packages
	// (GET /packages)
	ListPackages(c *gin.Context)
	// CreatePackage Create a membership package
	// (POST /packages)
	CreatePackage(c *gin.Context)
	// GetPackage Get a package by ID
	// (GET /packages/{packageId})
	GetPackage(c *gin.Context, packageId PackageID)
	// UpdatePackage Update a package
	// (PATCH /packages/{packageId})
	UpdatePackage(c *gin.Context, packageId PackageID)
	// CreateStaff Create a staff member
	// (POST /staff)
	CreateStaff(c *gin.Context)
	// GetStaff Get a staff member by ID
	// (GET /staff/{staffId})
	GetStaff(c *gin.Context, staffId StaffID)
	// UpdateStaff Update a staff member
	// (PATCH /staff/{staffId})
	UpdateStaff(c *gin.Context, staffId StaffID)
	// CreateTrainer Create a trainer
	// (POST /trainers)
	CreateTrainer(c *gin.Context)
	// GetTrainer Get a trainer by ID
	// (GET /trainers/{trainerId})
	GetTrainer(c *gin.Context, trainerId TrainerID)
	// UpdateTrainer Update a trainer
	// (PATCH /trainers/{trainerId})
	UpdateTrainer(c *gin.Context, trainerId TrainerID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CheckIn operation middleware
func (siw *ServerInterfaceWrapper) CheckIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckIn(c)
}

// CheckOut operation middleware
func (siw *ServerInterfaceWrapper) CheckOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckOut(c)
}

// GetAttendance operation middleware
func (siw *ServerInterfaceWrapper) GetAttendance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "attendanceId" -------------
	var attendanceId AttendanceID

	err = runtime.BindStyledParameterWithOptions("simple", "attendanceId", c.Param("attendanceId"), &attendanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter attendanceId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAttendance(c, attendanceId)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// CreateBooking operation middleware
func (siw *ServerInterfaceWrapper) CreateBooking(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateBooking(c)
}

// GetBooking operation middleware
func (siw *ServerInterfaceWrapper) GetBooking(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingID

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", c.Param("bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bookingId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBooking(c, bookingId)
}

// CancelBooking operation middleware
func (siw *ServerInterfaceWrapper) CancelBooking(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingID

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", c.Param("bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bookingId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelBooking(c, bookingId)
}

// ListBranches operation middleware
func (siw *ServerInterfaceWrapper) ListBranches(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBranchesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBranches(c, params)
}

// CreateBranch operation middleware
func (siw *ServerInterfaceWrapper) CreateBranch(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateBranch(c)
}

// GetBranch operation middleware
func (siw *ServerInterfaceWrapper) GetBranch(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "branchId" -------------
	var branchId BranchID

	err = runtime.BindStyledParameterWithOptions("simple", "branchId", c.Param("branchId"), &branchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter branchId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBranch(c, branchId)
}

// UpdateBranch operation middleware
func (siw *ServerInterfaceWrapper) UpdateBranch(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "branchId" -------------
	var branchId BranchID

	err = runtime.BindStyledParameterWithOptions("simple", "branchId", c.Param("branchId"), &branchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter branchId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateBranch(c, branchId)
}

// ListBranchStaff operation middleware
func (siw *ServerInterfaceWrapper) ListBranchStaff(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "branchId" -------------
	var branchId BranchID

	err = runtime.BindStyledParameterWithOptions("simple", "branchId", c.Param("branchId"), &branchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter branchId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBranchStaff(c, branchId)
}

// ListBranchTrainers operation middleware
func (siw *ServerInterfaceWrapper) ListBranchTrainers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "branchId" -------------
	var branchId BranchID

	err = runtime.BindStyledParameterWithOptions("simple", "branchId", c.Param("branchId"), &branchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter branchId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBranchTrainers(c, branchId)
}

// ListClasses operation middleware
func (siw *ServerInterfaceWrapper) ListClasses(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClassesParams

	// ------------- Optional query parameter "branchId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "branchId", c.Request.URL.Query(), &params.BranchId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter branchId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "trainerId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "trainerId", c.Request.URL.Query(), &params.TrainerId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trainerId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListClasses(c, params)
}

// CreateClass operation middleware
func (siw *ServerInterfaceWrapper) CreateClass(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateClass(c)
}

// DeleteClass operation middleware
func (siw *ServerInterfaceWrapper) DeleteClass(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "classId" -------------
	var classId ClassID

	err = runtime.BindStyledParameterWithOptions("simple", "classId", c.Param("classId"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter classId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteClass(c, classId)
}

// GetClass operation middleware
func (siw *ServerInterfaceWrapper) GetClass(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "classId" -------------
	var classId ClassID

	err = runtime.BindStyledParameterWithOptions("simple", "classId", c.Param("classId"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter classId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClass(c, classId)
}

// UpdateClass operation middleware
func (siw *ServerInterfaceWrapper) UpdateClass(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "classId" -------------
	var classId ClassID

	err = runtime.BindStyledParameterWithOptions("simple", "classId", c.Param("classId"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter classId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateClass(c, classId)
}

// ListClassBookings operation middleware
func (siw *ServerInterfaceWrapper) ListClassBookings(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "classId" -------------
	var classId ClassID

	err = runtime.BindStyledParameterWithOptions("simple", "classId", c.Param("classId"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter classId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListClassBookings(c, classId)
}

// CreateInvoice operation middleware
func (siw *ServerInterfaceWrapper) CreateInvoice(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvoice(c)
}

// GetInvoice operation middleware
func (siw *ServerInterfaceWrapper) GetInvoice(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId InvoiceID

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", c.Param("invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invoiceId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInvoice(c, invoiceId)
}

// UpdateInvoice operation middleware
func (siw *ServerInterfaceWrapper) UpdateInvoice(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId InvoiceID

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", c.Param("invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invoiceId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateInvoice(c, invoiceId)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMembers(c)
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMember(c)
}

// DeleteMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMember(c, memberId)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMember(c, memberId)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMember(c, memberId)
}

// ListMemberAttendance operation middleware
func (siw *ServerInterfaceWrapper) ListMemberAttendance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMemberAttendance(c, memberId)
}

// ListMemberInvoices operation middleware
func (siw *ServerInterfaceWrapper) ListMemberInvoices(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMemberInvoices(c, memberId)
}

// ListMemberMemberships operation middleware
func (siw *ServerInterfaceWrapper) ListMemberMemberships(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "memberId" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMemberMemberships(c, memberId)
}

// CreateMembership operation middleware
func (siw *ServerInterfaceWrapper) CreateMembership(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMembership(c)
}

// GetMembership operation middleware
func (siw *ServerInterfaceWrapper) GetMembership(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "membershipId" -------------
	var membershipId MembershipID

	err = runtime.BindStyledParameterWithOptions("simple", "membershipId", c.Param("membershipId"), &membershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter membershipId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMembership(c, membershipId)
}

// UpdateMembership operation middleware
func (siw *ServerInterfaceWrapper) UpdateMembership(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "membershipId" -------------
	var membershipId MembershipID

	err = runtime.BindStyledParameterWithOptions("simple", "membershipId", c.Param("membershipId"), &membershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter membershipId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMembership(c, membershipId)
}

// ListPackages operation middleware
func (siw *ServerInterfaceWrapper) ListPackages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPackages(c)
}

// CreatePackage operation middleware
func (siw *ServerInterfaceWrapper) CreatePackage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePackage(c)
}

// GetPackage operation middleware
func (siw *ServerInterfaceWrapper) GetPackage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "packageId" -------------
	var packageId PackageID

	err = runtime.BindStyledParameterWithOptions("simple", "packageId", c.Param("packageId"), &packageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter packageId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPackage(c, packageId)
}

// UpdatePackage operation middleware
func (siw *ServerInterfaceWrapper) UpdatePackage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "packageId" -------------
	var packageId PackageID

	err = runtime.BindStyledParameterWithOptions("simple", "packageId", c.Param("packageId"), &packageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter packageId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePackage(c, packageId)
}

// CreateStaff operation middleware
func (siw *ServerInterfaceWrapper) CreateStaff(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStaff(c)
}

// GetStaff operation middleware
func (siw *ServerInterfaceWrapper) GetStaff(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "staffId" -------------
	var staffId StaffID

	err = runtime.BindStyledParameterWithOptions("simple", "staffId", c.Param("staffId"), &staffId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter staffId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStaff(c, staffId)
}

// UpdateStaff operation middleware
func (siw *ServerInterfaceWrapper) UpdateStaff(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "staffId" -------------
	var staffId StaffID

	err = runtime.BindStyledParameterWithOptions("simple", "staffId", c.Param("staffId"), &staffId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter staffId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStaff(c, staffId)
}

// CreateTrainer operation middleware
func (siw *ServerInterfaceWrapper) CreateTrainer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTrainer(c)
}

// GetTrainer operation middleware
func (siw *ServerInterfaceWrapper) GetTrainer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "trainerId" -------------
	var trainerId TrainerID

	err = runtime.BindStyledParameterWithOptions("simple", "trainerId", c.Param("trainerId"), &trainerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trainerId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrainer(c, trainerId)
}

// UpdateTrainer operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrainer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "trainerId" -------------
	var trainerId TrainerID

	err = runtime.BindStyledParameterWithOptions("simple", "trainerId", c.Param("trainerId"), &trainerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trainerId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTrainer(c, trainerId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/branches", wrapper.ListBranches)
	router.POST(options.BaseURL+"/branches", wrapper.CreateBranch)
	router.GET(options.BaseURL+"/branches/:branchId", wrapper.GetBranch)
	router.PATCH(options.BaseURL+"/branches/:branchId", wrapper.UpdateBranch)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/members", wrapper.ListMembers)
	router.POST(options.BaseURL+"/members", wrapper.CreateMember)
	router.DELETE(options.BaseURL+"/members/:memberId", wrapper.DeleteMember)
	router.GET(options.BaseURL+"/members/:memberId", wrapper.GetMember)
	router.PATCH(options.BaseURL+"/members/:memberId", wrapper.UpdateMember)
	router.GET(options.BaseURL+"/members/:memberId/memberships", wrapper.ListMemberMemberships)
	router.GET(options.BaseURL+"/members/:memberId/attendance", wrapper.ListMemberAttendance)
	router.GET(options.BaseURL+"/members/:memberId/invoices", wrapper.ListMemberInvoices)
	router.POST(options.BaseURL+"/memberships", wrapper.CreateMembership)
	router.GET(options.BaseURL+"/memberships/:membershipId", wrapper.GetMembership)
	router.PATCH(options.BaseURL+"/memberships/:membershipId", wrapper.UpdateMembership)
	router.GET(options.BaseURL+"/packages", wrapper.ListPackages)
	router.POST(options.BaseURL+"/packages", wrapper.CreatePackage)
	router.GET(options.BaseURL+"/packages/:packageId", wrapper.GetPackage)
	router.PATCH(options.BaseURL+"/packages/:packageId", wrapper.UpdatePackage)
	router.GET(options.BaseURL+"/classes", wrapper.ListClasses)
	router.POST(options.BaseURL+"/classes", wrapper.CreateClass)
	router.DELETE(options.BaseURL+"/classes/:classId", wrapper.DeleteClass)
	router.GET(options.BaseURL+"/classes/:classId", wrapper.GetClass)
	router.PATCH(options.BaseURL+"/classes/:classId", wrapper.UpdateClass)
	router.GET(options.BaseURL+"/classes/:classId/bookings", wrapper.ListClassBookings)
	router.POST(options.BaseURL+"/bookings", wrapper.CreateBooking)
	router.GET(options.BaseURL+"/bookings/:bookingId", wrapper.GetBooking)
	router.POST(options.BaseURL+"/bookings/:bookingId/cancel", wrapper.CancelBooking)
	router.POST(options.BaseURL+"/attendance/check-in", wrapper.CheckIn)
	router.POST(options.BaseURL+"/attendance/check-out", wrapper.CheckOut)
	router.GET(options.BaseURL+"/attendance/:attendanceId", wrapper.GetAttendance)
	router.POST(options.BaseURL+"/invoices", wrapper.CreateInvoice)
	router.GET(options.BaseURL+"/invoices/:invoiceId", wrapper.GetInvoice)
	router.PATCH(options.BaseURL+"/invoices/:invoiceId", wrapper.UpdateInvoice)
	router.GET(options.BaseURL+"/branches/:branchId/staff", wrapper.ListBranchStaff)
	router.POST(options.BaseURL+"/staff", wrapper.CreateStaff)
	router.GET(options.BaseURL+"/staff/:staffId", wrapper.GetStaff)
	router.PATCH(options.BaseURL+"/staff/:staffId", wrapper.UpdateStaff)
	router.GET(options.BaseURL+"/branches/:branchId/trainers", wrapper.ListBranchTrainers)
	router.POST(options.BaseURL+"/trainers", wrapper.CreateTrainer)
	router.GET(options.BaseURL+"/trainers/:trainerId", wrapper.GetTrainer)
	router.PATCH(options.BaseURL+"/trainers/:trainerId", wrapper.UpdateTrainer)
}
